<style>
.as .row{display:flex;gap:32px;align-items:flex-end;flex-wrap:wrap}
.as .sum{width:240px;background:#fff;border:1px solid var(--gw-color-neutral-100);border-radius:12px;box-shadow:var(--gw-shadow-s2);padding:12px;display:flex;flex-direction:column;gap:12px}
.as .h{display:flex;justify-content:space-between}.as .h b{font:var(--gw-text-body-14-sem)}.as .h small{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-500)}
.as .stk{display:flex}.as .stk span{width:28px;height:28px;border-radius:50%;border:2px solid #fff;margin-left:-8px;overflow:hidden;background:var(--gw-color-neutral-100);display:grid;place-items:center;font:var(--gw-text-body-12-med)}.as .stk span:first-child{margin-left:0}.as .stk img{width:100%;height:100%;object-fit:cover}
.as .mtr{height:6px;border-radius:99px;background:var(--gw-color-neutral-100);overflow:hidden}.as .mtr i{display:block;height:100%;background:var(--gw-color-primary-500)}
.as .ln{display:flex;justify-content:space-between;font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600)}.as .ln b{color:#000}
.as .bk{display:flex;align-items:center;justify-content:center;gap:8px;height:36px;border-radius:8px;background:#000;color:#fff;font:var(--gw-text-button-14)}
.as .clr{text-align:center;font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600)}
.as .bar{display:flex;align-items:center;gap:12px;background:#000;color:#fff;border-radius:14px;padding:10px 10px 10px 14px;width:320px}
.as .bar b{display:block;font:var(--gw-text-body-14-sem)}.as .bar small{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-300)}
.as .bar .bw{margin-left:auto;background:#fff;color:#000;border-radius:8px;height:34px;padding:0 12px;display:flex;align-items:center;font:var(--gw-text-button-14)}
</style><div class="rvp as"><div class="vgroup"><div class="vhead"><code>agent-package-bar</code></div><div class="grid" style="--cellmin:320px"><div class="cell"><div class="stage g-light" style="align-items:flex-start;padding:24px;background:#f1f2f3"><div class="row"><div class="sum"><div class="h"><b>Your package</b><small>6 agents</small></div><div class="stk"><span><img src="/internal/staging/agent-store/assets/nuggets/binoculars.png"></span><span><img src="/internal/staging/agent-store/assets/nuggets/headphones.png"></span><span><img src="/internal/staging/agent-store/assets/nuggets/calculator.png"></span><span><img src="/internal/staging/agent-store/assets/nuggets/laptop.png"></span><span><img src="/internal/staging/agent-store/assets/nuggets/cap-ads.png"></span><span><img src="/internal/staging/agent-store/assets/nuggets/glasses-doc.png"></span></div><div><div class="mtr"><i style="width:100%"></i></div><div class="ln" style="margin-top:6px"><span>All slots used</span></div></div><div class="ln"><span>Growth</span><b>$1,100 / mo</b></div><div class="ln"><span>Priced separately</span><b>+ $2,000+</b></div><div class="bk">Build package <i style="display:inline-block;width:16px;height:16px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/arrow-right-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/arrow-right-bold.svg) center/contain no-repeat"></i></div><div class="clr">Clear</div></div><div><div style="font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600);margin-bottom:8px">Phone: bottom bar</div><div class="bar"><span style="width:28px;height:28px;border-radius:50%;overflow:hidden;display:block"><img src="/internal/staging/agent-store/assets/nuggets/headphones.png" style="width:100%;height:100%;object-fit:cover"></span><div><b>6 agents</b><small>Growth · $1,100 + $2,000+ / mo</small></div><span class="bw">Build</span></div></div></div></div><span class="cap">Desktop: a summary card under the categories in the sticky rail. Phone: a bottom bar. Both read the same package</span></div></div></div></div>
