<style>
.as .tb{display:flex;align-items:flex-end;gap:16px;border-bottom:1px solid var(--gw-color-neutral-100);width:640px}
.as .tabs{display:flex;gap:4px;flex:1;min-width:0;overflow:hidden}
.as .tab{display:inline-flex;align-items:center;gap:8px;height:48px;padding:0 12px;font:var(--gw-text-body-14-med);color:var(--gw-color-neutral-600);border-bottom:2px solid transparent;margin-bottom:-1px;white-space:nowrap}
.as .tab.on{color:#000;border-bottom-color:#000}.as .tab small{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-400)}
.as .srch{flex:none;width:200px;height:36px;margin-bottom:8px;display:flex;align-items:center;gap:8px;padding:0 12px;border:1px solid var(--gw-color-neutral-100);border-radius:8px;background:var(--gw-color-neutral-25);font:var(--gw-text-body-14-reg);color:var(--gw-color-neutral-500)}
.as .sum{width:240px;background:#fff;border:1px solid var(--gw-color-neutral-100);border-radius:12px;box-shadow:var(--gw-shadow-s2);padding:12px;display:flex;flex-direction:column;gap:12px}
.as .h{display:flex;justify-content:space-between}.as .h b{font:var(--gw-text-body-14-sem)}.as .h small{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-500)}
.as .it{display:flex;align-items:center;gap:8px;min-height:30px;font:var(--gw-text-body-14-med)}.as .it img{width:24px;height:24px;border-radius:50%;object-fit:cover}.as .it span{flex:1}.as .it i{color:var(--gw-color-neutral-500)}
.as .mtr{height:6px;border-radius:99px;background:var(--gw-color-neutral-100);overflow:hidden}.as .mtr i{display:block;height:100%;background:var(--gw-color-primary-500)}
.as .tr{display:flex;justify-content:space-between;align-items:center;height:28px;padding:0 8px;border-radius:8px;border:1px solid transparent;font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600)}.as .tr.best{background:var(--gw-color-primary-25);border-color:var(--gw-color-primary-100);color:var(--gw-color-primary-700)}
.as .tot small{display:block;font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600)}.as .tot b{font:var(--gw-text-h6-bold)}
.as .bk{display:flex;align-items:center;justify-content:center;gap:8px;height:36px;border-radius:8px;background:#000;color:#fff;font:var(--gw-text-button-14)}
.as .row{display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap}
</style><div class="rvp as"><div class="vgroup"><div class="vhead"><code>agent-package-panel</code></div><div class="grid" style="--cellmin:320px"><div class="cell"><div class="stage g-light" style="align-items:flex-start;padding:24px;background:#f1f2f3"><div class="sum"><div class="h"><b>Your package</b><small>3 agents</small></div><div class="it"><img src="/internal/staging/agent-store/assets/nuggets/headphones.png"><span>Quote Chaser</span><i style="display:inline-block;width:12px;height:12px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat"></i></div><div class="it"><img src="/internal/staging/agent-store/assets/nuggets/calculator.png"><span>Margin Guard</span><i style="display:inline-block;width:12px;height:12px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat"></i></div><div class="it"><img src="/internal/staging/agent-store/assets/nuggets/cap-ads.png"><span>Lead Chaser</span><i style="display:inline-block;width:12px;height:12px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat"></i></div><div><div class="mtr"><i style="width:100%"></i></div><div style="font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600);margin-top:6px">All slots used</div></div><div><div class="tr best"><span>Starter · 3 agents</span><b>$600</b></div><div class="tr"><span>Growth · 6 agents</span><b>$1,100</b></div><div class="tr"><span>Scale · 12 agents</span><b>$2,100</b></div></div><div class="tot"><small>Starter</small><b>$600 <span style="font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600)">/ mo</span></b></div><div class="bk">Build package <i style="display:inline-block;width:16px;height:16px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/arrow-right-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/arrow-right-bold.svg) center/contain no-repeat"></i></div></div></div><span class="cap">Version 2 package builder panel, sticky on the left: agents with remove, slots meter, tier ladder with the best price lit, total, Build package</span></div></div></div></div>
