<style>
.as .dlg{width:720px;background:var(--gw-color-neutral-25);border:1px solid var(--gw-color-neutral-100);border-radius:var(--gw-radius-20);box-shadow:var(--gw-shadow-s4);overflow:hidden}
.as .ph{display:flex;align-items:center;gap:12px;padding:12px 16px;border-bottom:1px solid var(--gw-color-neutral-100)}
.as .badge{display:inline-flex;align-items:center;height:22px;padding:2px 8px;border-radius:99px;background:var(--gw-color-neutral-50);font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-700)}
.as .pos{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-500)}
.as .nv{margin-left:auto;display:flex;gap:4px;align-items:center}
.as .ib{width:32px;height:32px;border-radius:8px;display:inline-flex;align-items:center;justify-content:center;color:var(--gw-color-neutral-700)}
.as .pb{display:grid;grid-template-columns:1.25fr 1fr;gap:32px;padding:24px}
.as .cl,.as .cr{display:flex;flex-direction:column;gap:20px;min-width:0}
.as .id{display:flex;gap:16px;align-items:center}.as .id img{width:96px;height:96px;border-radius:16px;object-fit:cover}
.as .id h2{font:var(--gw-text-h6-bold);margin-bottom:8px}.as .id .pr{font:var(--gw-text-body-14-med);color:var(--gw-color-primary-500)}
.as .steps{display:grid;grid-template-columns:76px 1fr;gap:8px 12px;font:var(--gw-text-body-14-reg)}.as .steps b{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-600);padding-top:2px}
.as .rep{background:var(--gw-color-primary-25);border:1px solid var(--gw-color-primary-100);border-radius:12px;padding:16px;display:flex;flex-direction:column;gap:12px;font:var(--gw-text-body-14-reg)}
.as .rep small{display:block;font:var(--gw-text-body-12-med);color:var(--gw-color-primary-700)}
.as .pf{padding:16px 24px;border-top:1px solid var(--gw-color-neutral-100);background:#fff}
.as .btnk{display:flex;justify-content:center;gap:8px;align-items:center;height:44px;border-radius:8px;background:var(--gw-color-black);color:#fff;font:var(--gw-text-button-16)}
</style><div class="rvp as"><div class="vgroup"><div class="vhead"><code>agent-listing-panel</code></div><div class="grid" style="--cellmin:320px"><div class="cell"><div class="stage g-light" style="align-items:flex-start;padding:24px;background:#f1f2f3"><div class="dlg"><div class="ph"><span class="badge">Lead to Quote</span><span class="pos">4 of 31</span><div class="nv"><span class="ib"><i style="display:inline-block;width:16px;height:16px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/arrow-left-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/arrow-left-bold.svg) center/contain no-repeat"></i></span><span class="ib"><i style="display:inline-block;width:16px;height:16px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/arrow-right-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/arrow-right-bold.svg) center/contain no-repeat"></i></span><span class="ib" style="margin-left:8px"><i style="display:inline-block;width:16px;height:16px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/x-bold.svg) center/contain no-repeat"></i></span></div></div><div class="pb"><div class="cl"><div class="id"><img src="/internal/staging/agent-store/assets/nuggets/headphones.png" alt=""><div><h2>Quote Chaser</h2><div style="font:var(--gw-text-body-14-med);color:var(--gw-color-neutral-700)">1 credit per quote chased</div></div></div><p>Follows up on every open quote until it is won, lost with a reason, or dead.</p><div class="steps"><b>Trigger</b><span>Starts when a quote has had no reply for 3 business days.</span><b>Reads</b><span>The quote, past emails, expiry date and rep notes.</span><b>Does</b><span>Sends follow-ups from the rep’s mailbox.</span></div></div><div class="cr"><div class="rep"><div><small>Pain to listen for</small>Quotes go out, nobody follows up.</div><div><small>Discovery question</small>“Of last month’s quotes, how many do you know the outcome of?”</div></div></div></div><div class="pf"><div class="btnk"><i style="display:inline-block;width:16px;height:16px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/plus-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/plus-bold.svg) center/contain no-repeat"></i>Add to package</div></div></div></div><span class="cap">Centered modal with previous and next, a position count and close. Two columns on desktop, a bottom sheet on phone</span></div></div></div></div>
