<style>
.as .bar{display:flex;align-items:center;justify-content:space-between;gap:16px;width:760px}
.as .cap2{display:flex;background:#fff;border:1px solid var(--gw-color-neutral-100);border-radius:999px;padding:4px;box-shadow:var(--gw-shadow-s2)}
.as .pl{display:inline-flex;align-items:center;gap:8px;height:36px;padding:0 12px;border-radius:999px;font:var(--gw-text-body-14-med);color:var(--gw-color-neutral-700);white-space:nowrap}
.as .pl small{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-400)}
.as .pl.on{background:#000;color:#fff}.as .pl.on small{color:var(--gw-color-neutral-300)}
.as .dd{display:flex;align-items:center;gap:8px;height:36px;padding:0 12px;border:1px solid var(--gw-color-neutral-100);border-radius:8px;background:#fff;font:var(--gw-text-body-14-med);width:200px}
.as .dd small{font:var(--gw-text-body-12-med);color:var(--gw-color-neutral-500)}
</style><div class="rvp as"><div class="vgroup"><div class="vhead"><code>agent-category-toggle</code></div><div class="grid" style="--cellmin:320px"><div class="cell"><div class="stage g-light" style="align-items:flex-start;padding:24px;background:#f1f2f3"><div class="bar"><div class="cap2"><span class="pl on">Generate more leads <small>3</small></span><span class="pl">Lead to Quote <small>7</small></span><span class="pl">Order Desk <small>6</small></span><span class="pl">Purchasing <small>6</small></span></div><div class="dd"><small>Industry</small>Manufacturers<span style="margin-left:auto"><i style="display:inline-block;width:16px;height:16px;background:currentColor;-webkit-mask:url(/internal/staging/agent-store/assets/icons/caret-down-bold.svg) center/contain no-repeat;mask:url(/internal/staging/agent-store/assets/icons/caret-down-bold.svg) center/contain no-repeat"></i></span></div></div></div><span class="cap">Version 3: the category tabs as a pill toggle. White capsule, black active pill, count in each pill, the industry dropdown at the right end</span></div></div></div></div>
