<div class="rvp"><div class="vgroup"><div class="vhead"><code>layout/Split card</code><span class="scl">1920 × 1080</span></div><div class="foldwrap"><div class="foldscale" style="width:1920px;zoom:0.5"><style>
.sc{position:relative;width:1920px;height:1080px;overflow:hidden;background:var(--gw-color-primary-500,#0070ff);font-family:var(--gw-font-body,'Plus Jakarta Sans',sans-serif);-webkit-font-smoothing:antialiased}
.sc *{box-sizing:border-box}
.sc::before{content:"";position:absolute;inset:0;pointer-events:none;opacity:.3;background-image:linear-gradient(to right,#fff 1px,transparent 1px),linear-gradient(to bottom,#fff 1px,transparent 1px);background-size:40px 40px;background-position:-.5px -.5px;-webkit-mask-image:radial-gradient(60% 70% at 50% 50%,transparent 0%,#000 100%);mask-image:radial-gradient(60% 70% at 50% 50%,transparent 0%,#000 100%)}
.sc-title{position:absolute;left:40px;top:38px;width:1723.2px;margin:0;font:700 72px/1.2 var(--gw-font-slide-display,'Vert Grotesk Display','Plus Jakarta Sans',sans-serif);color:var(--gw-color-white,#fff)}
.sc-card{position:absolute;left:20px;right:20px;top:178.2px;height:884px;background:var(--gw-color-white,#fff);border:1.3px solid var(--gw-color-neutral-200,#cfd1d4);border-radius:var(--gw-radius-36,36px)}
.sc-well{position:absolute;left:18.7px;top:14.5px;width:779px;height:852.3px;border-radius:var(--gw-radius-28,28px);overflow:hidden;background-color:var(--gw-color-neutral-25,#f7f8f9);background-image:linear-gradient(to right,var(--gw-color-neutral-200,#cfd1d4) 1px,transparent 1px),linear-gradient(to bottom,var(--gw-color-neutral-200,#cfd1d4) 1px,transparent 1px);background-size:40px 40px;display:flex;align-items:flex-end;justify-content:center;padding-bottom:40px}
.sc-well span{font:500 22px/1.4 var(--gw-font-body,sans-serif);color:var(--gw-color-neutral-600,#6a7077);background:var(--gw-color-white,#fff);border-radius:12px;padding:8px 16px}
.sc-lead{position:absolute;left:47.7px;top:48px;width:694.6px;margin:0;font:500 26px/1.4 var(--gw-font-body,sans-serif);color:var(--gw-color-neutral-850,#2e3338)}
.sc-lead b{font-weight:600;color:var(--gw-color-primary-500,#0070ff)}
</style><div class="sc"><h2 class="sc-title">Slide title sits on the ground</h2><div class="sc-card"><div class="sc-well"><span>Media well: texture frame, cutout sits at the bottom</span></div><p class="sc-lead">Lead paragraph on the left of the media well. <b>One outcome phrase in blue.</b></p></div></div></div></div></div></div>
