<div class="rvp"><div class="vgroup"><div class="vhead"><code>Generate report: form, ready, error</code></div><div class="grid" style="--cellmin:480px"><div class="cell"><div class="stage g-light" style="color-scheme:light;"><div class="gd" style="width:100%;background:none;"><div class="gd-modal gd-modal--static gd-modal--md" style="--_w:480px" role="dialog" aria-labelledby="gen-report-t-form">
  <div class="gd-modal__head"><div><h2 class="gd-modal__title" id="gen-report-t-form">Generate report</h2><p class="gd-modal__desc">A report page you can share as a link. It is a snapshot of the data as it is now.</p></div><button type="button" class="gd-fb-close" data-gd-close aria-label="Close"><svg viewBox="0 0 256 256" width="16" height="16" fill="currentColor" aria-hidden="true" focusable="false"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"/></svg></button></div>
  <div class="gd-modal__body">
    <div class="gd-gr__fields" data-gd-gr="form">
      <div class="gd-field"><span class="gd-field__label" id="gen-report-range">Time range</span>
        <div class="gd-select" data-gd-select><button type="button" class="gd-input" aria-haspopup="listbox" aria-labelledby="gen-report-range"><span class="gd-select__value">This dashboard&rsquo;s range</span><svg class="gd-input__caret" viewBox="0 0 256 256" fill="currentColor" width="12" height="12" aria-hidden="true"><path d="M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z"/></svg></button>
          <div class="gd-menu" role="listbox" hidden><button type="button" class="gd-menu__item" role="option" data-value="dashboard" aria-selected="true"><span class="gd-menu__text"><span>This dashboard&rsquo;s range</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="7d" aria-selected="false"><span class="gd-menu__text"><span>Last 7 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="30d" aria-selected="false"><span class="gd-menu__text"><span>Last 30 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="90d" aria-selected="false"><span class="gd-menu__text"><span>Last 90 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button></div><input type="hidden" name="range" value="dashboard"></div>
        <p class="gd-field__help">The report names its range and compares it with the period before.</p></div>
      <fieldset class="gd-field gd-gr__set"><legend class="gd-field__label">Sections</legend>
        <div class="gd-gr__list"><label class="gd-check"><input type="checkbox" name="section" value="numbers" checked><span class="gd-check__box"></span><span class="gd-check__label">Headline numbers</span></label><label class="gd-check"><input type="checkbox" name="section" value="trends" checked><span class="gd-check__box"></span><span class="gd-check__label">Trends over time</span></label><label class="gd-check"><input type="checkbox" name="section" value="breakdown" checked><span class="gd-check__box"></span><span class="gd-check__label">Breakdown by channel</span></label><label class="gd-check"><input type="checkbox" name="section" value="table" checked><span class="gd-check__box"></span><span class="gd-check__label">Tables</span></label></div>
        <p class="gd-field__error" role="alert" data-gd-gr-need hidden>Pick at least one section.</p></fieldset>
    </div>
    <div hidden data-gd-gr="working" role="status" aria-live="polite"><p class="gd-gr__msg">Making your report&hellip;</p></div>
    <div hidden data-gd-gr="ready">
      <div class="gd-field"><label class="gd-field__label" for="gen-report-url">Link to the report</label><div class="gd-input"><input id="gen-report-url" class="gd-input__el" data-gd-gr-url readonly value="https://reports.example.test/r/4f9a2c"></div>
        <p class="gd-field__help">Anyone who can open the link sees the report as it is now. It does not update.</p></div>
    </div>
    <div hidden data-gd-gr="error"><p class="gd-gr__msg" role="alert" data-gd-gr-message>The report could not be made.</p></div>
  </div>
  <div class="gd-modal__foot">
    <button type="button" class="gd-btn gd-btn--outline" data-gd-close data-gd-gr="form working error">Cancel</button>
    <button type="button" class="gd-btn gd-btn--primary" data-gd-gr-submit data-gd-gr="form working">Generate report</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-retry hidden data-gd-gr="error">Try again</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-copy hidden data-gd-gr="ready">Copy link</button>
    <a class="gd-btn gd-btn--primary" data-gd-gr-open hidden data-gd-gr="ready" href="#" target="_blank" rel="noopener">Open report</a>
  </div>
</div></div></div><span class="cap">Choose a range and the sections · light</span></div><div class="cell"><div class="stage g-dark" style="color-scheme:dark;"><div class="gd" style="width:100%;background:none;"><div class="gd-modal gd-modal--static gd-modal--md" style="--_w:480px" role="dialog" aria-labelledby="gen-report-t-form">
  <div class="gd-modal__head"><div><h2 class="gd-modal__title" id="gen-report-t-form">Generate report</h2><p class="gd-modal__desc">A report page you can share as a link. It is a snapshot of the data as it is now.</p></div><button type="button" class="gd-fb-close" data-gd-close aria-label="Close"><svg viewBox="0 0 256 256" width="16" height="16" fill="currentColor" aria-hidden="true" focusable="false"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"/></svg></button></div>
  <div class="gd-modal__body">
    <div class="gd-gr__fields" data-gd-gr="form">
      <div class="gd-field"><span class="gd-field__label" id="gen-report-range">Time range</span>
        <div class="gd-select" data-gd-select><button type="button" class="gd-input" aria-haspopup="listbox" aria-labelledby="gen-report-range"><span class="gd-select__value">This dashboard&rsquo;s range</span><svg class="gd-input__caret" viewBox="0 0 256 256" fill="currentColor" width="12" height="12" aria-hidden="true"><path d="M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z"/></svg></button>
          <div class="gd-menu" role="listbox" hidden><button type="button" class="gd-menu__item" role="option" data-value="dashboard" aria-selected="true"><span class="gd-menu__text"><span>This dashboard&rsquo;s range</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="7d" aria-selected="false"><span class="gd-menu__text"><span>Last 7 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="30d" aria-selected="false"><span class="gd-menu__text"><span>Last 30 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="90d" aria-selected="false"><span class="gd-menu__text"><span>Last 90 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button></div><input type="hidden" name="range" value="dashboard"></div>
        <p class="gd-field__help">The report names its range and compares it with the period before.</p></div>
      <fieldset class="gd-field gd-gr__set"><legend class="gd-field__label">Sections</legend>
        <div class="gd-gr__list"><label class="gd-check"><input type="checkbox" name="section" value="numbers" checked><span class="gd-check__box"></span><span class="gd-check__label">Headline numbers</span></label><label class="gd-check"><input type="checkbox" name="section" value="trends" checked><span class="gd-check__box"></span><span class="gd-check__label">Trends over time</span></label><label class="gd-check"><input type="checkbox" name="section" value="breakdown" checked><span class="gd-check__box"></span><span class="gd-check__label">Breakdown by channel</span></label><label class="gd-check"><input type="checkbox" name="section" value="table" checked><span class="gd-check__box"></span><span class="gd-check__label">Tables</span></label></div>
        <p class="gd-field__error" role="alert" data-gd-gr-need hidden>Pick at least one section.</p></fieldset>
    </div>
    <div hidden data-gd-gr="working" role="status" aria-live="polite"><p class="gd-gr__msg">Making your report&hellip;</p></div>
    <div hidden data-gd-gr="ready">
      <div class="gd-field"><label class="gd-field__label" for="gen-report-url">Link to the report</label><div class="gd-input"><input id="gen-report-url" class="gd-input__el" data-gd-gr-url readonly value="https://reports.example.test/r/4f9a2c"></div>
        <p class="gd-field__help">Anyone who can open the link sees the report as it is now. It does not update.</p></div>
    </div>
    <div hidden data-gd-gr="error"><p class="gd-gr__msg" role="alert" data-gd-gr-message>The report could not be made.</p></div>
  </div>
  <div class="gd-modal__foot">
    <button type="button" class="gd-btn gd-btn--outline" data-gd-close data-gd-gr="form working error">Cancel</button>
    <button type="button" class="gd-btn gd-btn--primary" data-gd-gr-submit data-gd-gr="form working">Generate report</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-retry hidden data-gd-gr="error">Try again</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-copy hidden data-gd-gr="ready">Copy link</button>
    <a class="gd-btn gd-btn--primary" data-gd-gr-open hidden data-gd-gr="ready" href="#" target="_blank" rel="noopener">Open report</a>
  </div>
</div></div></div><span class="cap">Choose a range and the sections · dark</span></div><div class="cell"><div class="stage g-light" style="color-scheme:light;"><div class="gd" style="width:100%;background:none;"><div class="gd-modal gd-modal--static gd-modal--md" style="--_w:480px" role="dialog" aria-labelledby="gen-report-t-ready">
  <div class="gd-modal__head"><div><h2 class="gd-modal__title" id="gen-report-t-ready">Generate report</h2><p class="gd-modal__desc">A report page you can share as a link. It is a snapshot of the data as it is now.</p></div><button type="button" class="gd-fb-close" data-gd-close aria-label="Close"><svg viewBox="0 0 256 256" width="16" height="16" fill="currentColor" aria-hidden="true" focusable="false"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"/></svg></button></div>
  <div class="gd-modal__body">
    <div class="gd-gr__fields" hidden data-gd-gr="form">
      <div class="gd-field"><span class="gd-field__label" id="gen-report-range">Time range</span>
        <div class="gd-select" data-gd-select><button type="button" class="gd-input" aria-haspopup="listbox" aria-labelledby="gen-report-range"><span class="gd-select__value">This dashboard&rsquo;s range</span><svg class="gd-input__caret" viewBox="0 0 256 256" fill="currentColor" width="12" height="12" aria-hidden="true"><path d="M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z"/></svg></button>
          <div class="gd-menu" role="listbox" hidden><button type="button" class="gd-menu__item" role="option" data-value="dashboard" aria-selected="true"><span class="gd-menu__text"><span>This dashboard&rsquo;s range</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="7d" aria-selected="false"><span class="gd-menu__text"><span>Last 7 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="30d" aria-selected="false"><span class="gd-menu__text"><span>Last 30 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="90d" aria-selected="false"><span class="gd-menu__text"><span>Last 90 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button></div><input type="hidden" name="range" value="dashboard"></div>
        <p class="gd-field__help">The report names its range and compares it with the period before.</p></div>
      <fieldset class="gd-field gd-gr__set"><legend class="gd-field__label">Sections</legend>
        <div class="gd-gr__list"><label class="gd-check"><input type="checkbox" name="section" value="numbers" checked><span class="gd-check__box"></span><span class="gd-check__label">Headline numbers</span></label><label class="gd-check"><input type="checkbox" name="section" value="trends" checked><span class="gd-check__box"></span><span class="gd-check__label">Trends over time</span></label><label class="gd-check"><input type="checkbox" name="section" value="breakdown" checked><span class="gd-check__box"></span><span class="gd-check__label">Breakdown by channel</span></label><label class="gd-check"><input type="checkbox" name="section" value="table" checked><span class="gd-check__box"></span><span class="gd-check__label">Tables</span></label></div>
        <p class="gd-field__error" role="alert" data-gd-gr-need hidden>Pick at least one section.</p></fieldset>
    </div>
    <div hidden data-gd-gr="working" role="status" aria-live="polite"><p class="gd-gr__msg">Making your report&hellip;</p></div>
    <div data-gd-gr="ready">
      <div class="gd-field"><label class="gd-field__label" for="gen-report-url">Link to the report</label><div class="gd-input"><input id="gen-report-url" class="gd-input__el" data-gd-gr-url readonly value="https://reports.example.test/r/4f9a2c"></div>
        <p class="gd-field__help">Anyone who can open the link sees the report as it is now. It does not update.</p></div>
    </div>
    <div hidden data-gd-gr="error"><p class="gd-gr__msg" role="alert" data-gd-gr-message>The report could not be made.</p></div>
  </div>
  <div class="gd-modal__foot">
    <button type="button" class="gd-btn gd-btn--outline" data-gd-close hidden data-gd-gr="form working error">Cancel</button>
    <button type="button" class="gd-btn gd-btn--primary" data-gd-gr-submit hidden data-gd-gr="form working">Generate report</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-retry hidden data-gd-gr="error">Try again</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-copy data-gd-gr="ready">Copy link</button>
    <a class="gd-btn gd-btn--primary" data-gd-gr-open data-gd-gr="ready" href="#" target="_blank" rel="noopener">Open report</a>
  </div>
</div></div></div><span class="cap">The link, once the page has made the report · light</span></div><div class="cell"><div class="stage g-dark" style="color-scheme:dark;"><div class="gd" style="width:100%;background:none;"><div class="gd-modal gd-modal--static gd-modal--md" style="--_w:480px" role="dialog" aria-labelledby="gen-report-t-ready">
  <div class="gd-modal__head"><div><h2 class="gd-modal__title" id="gen-report-t-ready">Generate report</h2><p class="gd-modal__desc">A report page you can share as a link. It is a snapshot of the data as it is now.</p></div><button type="button" class="gd-fb-close" data-gd-close aria-label="Close"><svg viewBox="0 0 256 256" width="16" height="16" fill="currentColor" aria-hidden="true" focusable="false"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"/></svg></button></div>
  <div class="gd-modal__body">
    <div class="gd-gr__fields" hidden data-gd-gr="form">
      <div class="gd-field"><span class="gd-field__label" id="gen-report-range">Time range</span>
        <div class="gd-select" data-gd-select><button type="button" class="gd-input" aria-haspopup="listbox" aria-labelledby="gen-report-range"><span class="gd-select__value">This dashboard&rsquo;s range</span><svg class="gd-input__caret" viewBox="0 0 256 256" fill="currentColor" width="12" height="12" aria-hidden="true"><path d="M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z"/></svg></button>
          <div class="gd-menu" role="listbox" hidden><button type="button" class="gd-menu__item" role="option" data-value="dashboard" aria-selected="true"><span class="gd-menu__text"><span>This dashboard&rsquo;s range</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="7d" aria-selected="false"><span class="gd-menu__text"><span>Last 7 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="30d" aria-selected="false"><span class="gd-menu__text"><span>Last 30 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="90d" aria-selected="false"><span class="gd-menu__text"><span>Last 90 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button></div><input type="hidden" name="range" value="dashboard"></div>
        <p class="gd-field__help">The report names its range and compares it with the period before.</p></div>
      <fieldset class="gd-field gd-gr__set"><legend class="gd-field__label">Sections</legend>
        <div class="gd-gr__list"><label class="gd-check"><input type="checkbox" name="section" value="numbers" checked><span class="gd-check__box"></span><span class="gd-check__label">Headline numbers</span></label><label class="gd-check"><input type="checkbox" name="section" value="trends" checked><span class="gd-check__box"></span><span class="gd-check__label">Trends over time</span></label><label class="gd-check"><input type="checkbox" name="section" value="breakdown" checked><span class="gd-check__box"></span><span class="gd-check__label">Breakdown by channel</span></label><label class="gd-check"><input type="checkbox" name="section" value="table" checked><span class="gd-check__box"></span><span class="gd-check__label">Tables</span></label></div>
        <p class="gd-field__error" role="alert" data-gd-gr-need hidden>Pick at least one section.</p></fieldset>
    </div>
    <div hidden data-gd-gr="working" role="status" aria-live="polite"><p class="gd-gr__msg">Making your report&hellip;</p></div>
    <div data-gd-gr="ready">
      <div class="gd-field"><label class="gd-field__label" for="gen-report-url">Link to the report</label><div class="gd-input"><input id="gen-report-url" class="gd-input__el" data-gd-gr-url readonly value="https://reports.example.test/r/4f9a2c"></div>
        <p class="gd-field__help">Anyone who can open the link sees the report as it is now. It does not update.</p></div>
    </div>
    <div hidden data-gd-gr="error"><p class="gd-gr__msg" role="alert" data-gd-gr-message>The report could not be made.</p></div>
  </div>
  <div class="gd-modal__foot">
    <button type="button" class="gd-btn gd-btn--outline" data-gd-close hidden data-gd-gr="form working error">Cancel</button>
    <button type="button" class="gd-btn gd-btn--primary" data-gd-gr-submit hidden data-gd-gr="form working">Generate report</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-retry hidden data-gd-gr="error">Try again</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-copy data-gd-gr="ready">Copy link</button>
    <a class="gd-btn gd-btn--primary" data-gd-gr-open data-gd-gr="ready" href="#" target="_blank" rel="noopener">Open report</a>
  </div>
</div></div></div><span class="cap">The link, once the page has made the report · dark</span></div><div class="cell"><div class="stage g-light" style="color-scheme:light;"><div class="gd" style="width:100%;background:none;"><div class="gd-modal gd-modal--static gd-modal--md" style="--_w:480px" role="dialog" aria-labelledby="gen-report-t-error">
  <div class="gd-modal__head"><div><h2 class="gd-modal__title" id="gen-report-t-error">Generate report</h2><p class="gd-modal__desc">A report page you can share as a link. It is a snapshot of the data as it is now.</p></div><button type="button" class="gd-fb-close" data-gd-close aria-label="Close"><svg viewBox="0 0 256 256" width="16" height="16" fill="currentColor" aria-hidden="true" focusable="false"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"/></svg></button></div>
  <div class="gd-modal__body">
    <div class="gd-gr__fields" hidden data-gd-gr="form">
      <div class="gd-field"><span class="gd-field__label" id="gen-report-range">Time range</span>
        <div class="gd-select" data-gd-select><button type="button" class="gd-input" aria-haspopup="listbox" aria-labelledby="gen-report-range"><span class="gd-select__value">This dashboard&rsquo;s range</span><svg class="gd-input__caret" viewBox="0 0 256 256" fill="currentColor" width="12" height="12" aria-hidden="true"><path d="M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z"/></svg></button>
          <div class="gd-menu" role="listbox" hidden><button type="button" class="gd-menu__item" role="option" data-value="dashboard" aria-selected="true"><span class="gd-menu__text"><span>This dashboard&rsquo;s range</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="7d" aria-selected="false"><span class="gd-menu__text"><span>Last 7 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="30d" aria-selected="false"><span class="gd-menu__text"><span>Last 30 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="90d" aria-selected="false"><span class="gd-menu__text"><span>Last 90 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button></div><input type="hidden" name="range" value="dashboard"></div>
        <p class="gd-field__help">The report names its range and compares it with the period before.</p></div>
      <fieldset class="gd-field gd-gr__set"><legend class="gd-field__label">Sections</legend>
        <div class="gd-gr__list"><label class="gd-check"><input type="checkbox" name="section" value="numbers" checked><span class="gd-check__box"></span><span class="gd-check__label">Headline numbers</span></label><label class="gd-check"><input type="checkbox" name="section" value="trends" checked><span class="gd-check__box"></span><span class="gd-check__label">Trends over time</span></label><label class="gd-check"><input type="checkbox" name="section" value="breakdown" checked><span class="gd-check__box"></span><span class="gd-check__label">Breakdown by channel</span></label><label class="gd-check"><input type="checkbox" name="section" value="table" checked><span class="gd-check__box"></span><span class="gd-check__label">Tables</span></label></div>
        <p class="gd-field__error" role="alert" data-gd-gr-need hidden>Pick at least one section.</p></fieldset>
    </div>
    <div hidden data-gd-gr="working" role="status" aria-live="polite"><p class="gd-gr__msg">Making your report&hellip;</p></div>
    <div hidden data-gd-gr="ready">
      <div class="gd-field"><label class="gd-field__label" for="gen-report-url">Link to the report</label><div class="gd-input"><input id="gen-report-url" class="gd-input__el" data-gd-gr-url readonly value="https://reports.example.test/r/4f9a2c"></div>
        <p class="gd-field__help">Anyone who can open the link sees the report as it is now. It does not update.</p></div>
    </div>
    <div data-gd-gr="error"><p class="gd-gr__msg" role="alert" data-gd-gr-message>The report could not be made.</p></div>
  </div>
  <div class="gd-modal__foot">
    <button type="button" class="gd-btn gd-btn--outline" data-gd-close data-gd-gr="form working error">Cancel</button>
    <button type="button" class="gd-btn gd-btn--primary" data-gd-gr-submit hidden data-gd-gr="form working">Generate report</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-retry data-gd-gr="error">Try again</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-copy hidden data-gd-gr="ready">Copy link</button>
    <a class="gd-btn gd-btn--primary" data-gd-gr-open hidden data-gd-gr="ready" href="#" target="_blank" rel="noopener">Open report</a>
  </div>
</div></div></div><span class="cap">When it fails, or nothing is connected · light</span></div><div class="cell"><div class="stage g-dark" style="color-scheme:dark;"><div class="gd" style="width:100%;background:none;"><div class="gd-modal gd-modal--static gd-modal--md" style="--_w:480px" role="dialog" aria-labelledby="gen-report-t-error">
  <div class="gd-modal__head"><div><h2 class="gd-modal__title" id="gen-report-t-error">Generate report</h2><p class="gd-modal__desc">A report page you can share as a link. It is a snapshot of the data as it is now.</p></div><button type="button" class="gd-fb-close" data-gd-close aria-label="Close"><svg viewBox="0 0 256 256" width="16" height="16" fill="currentColor" aria-hidden="true" focusable="false"><path d="M205.66,194.34a8,8,0,0,1-11.32,11.32L128,139.31,61.66,205.66a8,8,0,0,1-11.32-11.32L116.69,128,50.34,61.66A8,8,0,0,1,61.66,50.34L128,116.69l66.34-66.35a8,8,0,0,1,11.32,11.32L139.31,128Z"/></svg></button></div>
  <div class="gd-modal__body">
    <div class="gd-gr__fields" hidden data-gd-gr="form">
      <div class="gd-field"><span class="gd-field__label" id="gen-report-range">Time range</span>
        <div class="gd-select" data-gd-select><button type="button" class="gd-input" aria-haspopup="listbox" aria-labelledby="gen-report-range"><span class="gd-select__value">This dashboard&rsquo;s range</span><svg class="gd-input__caret" viewBox="0 0 256 256" fill="currentColor" width="12" height="12" aria-hidden="true"><path d="M216.49,104.49l-80,80a12,12,0,0,1-17,0l-80-80a12,12,0,0,1,17-17L128,159l71.51-71.52a12,12,0,0,1,17,17Z"/></svg></button>
          <div class="gd-menu" role="listbox" hidden><button type="button" class="gd-menu__item" role="option" data-value="dashboard" aria-selected="true"><span class="gd-menu__text"><span>This dashboard&rsquo;s range</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="7d" aria-selected="false"><span class="gd-menu__text"><span>Last 7 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="30d" aria-selected="false"><span class="gd-menu__text"><span>Last 30 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button><button type="button" class="gd-menu__item" role="option" data-value="90d" aria-selected="false"><span class="gd-menu__text"><span>Last 90 days</span></span><svg class="gd-menu__check" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true"><path d="M232.49,80.49l-128,128a12,12,0,0,1-17,0l-56-56a12,12,0,1,1,17-17L96,183,215.51,63.51a12,12,0,0,1,17,17Z"/></svg></button></div><input type="hidden" name="range" value="dashboard"></div>
        <p class="gd-field__help">The report names its range and compares it with the period before.</p></div>
      <fieldset class="gd-field gd-gr__set"><legend class="gd-field__label">Sections</legend>
        <div class="gd-gr__list"><label class="gd-check"><input type="checkbox" name="section" value="numbers" checked><span class="gd-check__box"></span><span class="gd-check__label">Headline numbers</span></label><label class="gd-check"><input type="checkbox" name="section" value="trends" checked><span class="gd-check__box"></span><span class="gd-check__label">Trends over time</span></label><label class="gd-check"><input type="checkbox" name="section" value="breakdown" checked><span class="gd-check__box"></span><span class="gd-check__label">Breakdown by channel</span></label><label class="gd-check"><input type="checkbox" name="section" value="table" checked><span class="gd-check__box"></span><span class="gd-check__label">Tables</span></label></div>
        <p class="gd-field__error" role="alert" data-gd-gr-need hidden>Pick at least one section.</p></fieldset>
    </div>
    <div hidden data-gd-gr="working" role="status" aria-live="polite"><p class="gd-gr__msg">Making your report&hellip;</p></div>
    <div hidden data-gd-gr="ready">
      <div class="gd-field"><label class="gd-field__label" for="gen-report-url">Link to the report</label><div class="gd-input"><input id="gen-report-url" class="gd-input__el" data-gd-gr-url readonly value="https://reports.example.test/r/4f9a2c"></div>
        <p class="gd-field__help">Anyone who can open the link sees the report as it is now. It does not update.</p></div>
    </div>
    <div data-gd-gr="error"><p class="gd-gr__msg" role="alert" data-gd-gr-message>The report could not be made.</p></div>
  </div>
  <div class="gd-modal__foot">
    <button type="button" class="gd-btn gd-btn--outline" data-gd-close data-gd-gr="form working error">Cancel</button>
    <button type="button" class="gd-btn gd-btn--primary" data-gd-gr-submit hidden data-gd-gr="form working">Generate report</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-retry data-gd-gr="error">Try again</button>
    <button type="button" class="gd-btn gd-btn--outline" data-gd-gr-copy hidden data-gd-gr="ready">Copy link</button>
    <a class="gd-btn gd-btn--primary" data-gd-gr-open hidden data-gd-gr="ready" href="#" target="_blank" rel="noopener">Open report</a>
  </div>
</div></div></div><span class="cap">When it fails, or nothing is connected · dark</span></div></div></div></div>
